const map=L.map("map",{zoomControl:true}).setView([6.5244,3.3792],7);
const base=L.tileLayer("https://tile.openstreetmap.org/{z}/{x}/{y}.png",{maxZoom:19,attribution:"© OpenStreetMap contributors"}).addTo(map);
let sat=null,cloud=null,marker=null,deviceMarker=null,lat=6.5244,lng=3.3792;
const $=id=>document.getElementById(id);
function nasa(layer,nrt=false,opacity=1){return L.tileLayer.wms(`https://gibs.earthdata.nasa.gov/wms/epsg3857/${nrt?"nrt":"best"}/wms.cgi`,{layers:layer,format:"image/png",transparent:true,version:"1.1.1",opacity,attribution:"NASA GIBS"})}
function selectPoint(a,b,name="LOCATION"){lat=a;lng=b;if(marker)map.removeLayer(marker);marker=L.marker([a,b]).addTo(map);$("place").innerHTML=`<b>${escapeHtml(name)}</b><small>LAT ${a.toFixed(6)} / LNG ${b.toFixed(6)}</small>`;loadPhotos(a,b);updateCoords()}
function escapeHtml(s){return String(s).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}
function updateCoords(){$("coords").textContent=`LAT ${lat.toFixed(6)} / LNG ${lng.toFixed(6)} / Z ${map.getZoom()}`}
map.on("zoomend moveend",updateCoords);map.on("click",e=>selectPoint(e.latlng.lat,e.latlng.lng,"MAP SELECTION"));
function loadPhotos(a,b){$("streetStatus").textContent="QUERY";$("status").textContent="SEARCHING PUBLIC STREET IMAGERY…";$("photos").innerHTML="";if($("quality").value==="low"){ $("status").textContent="LOW DATA MODE: street photos load only when requested.";$("streetStatus").textContent="SAVER";return }fetch(`https://api.openstreetcam.org/2.0/photo/?lat=${a}&lng=${b}&radius=500`).then(r=>r.json()).then(j=>{const list=Array.isArray(j.result?.data)?j.result.data:(Array.isArray(j.result)?j.result:[]);if(!list.length){$("status").textContent="NO PUBLIC STREET PHOTOS WITHIN ~500 M";$("streetStatus").textContent="NO COVERAGE";return}$("status").textContent=`FOUND ${Math.min(list.length,8)} PUBLIC STREET IMAGE(S)`;$("streetStatus").textContent="ONLINE";list.slice(0,8).forEach(p=>{const src=p.lth_name||p.name||p.image||p.url||p.photo_url||p.fileurl;if(!src)return;const d=document.createElement("div");d.className="photo";d.innerHTML=`<img loading="lazy" src="${src}" alt="Street image"><span>${p.date_processed||p.date_added||"PUBLIC IMAGE"}</span>`;d.onclick=()=>{$("big").src=src;$("caption").textContent="KARTAVIEW // PUBLIC STREET IMAGERY";$("viewer").classList.remove("hidden")};$("photos").appendChild(d)})}).catch(()=>{$("streetStatus").textContent="OFFLINE";$("status").textContent="STREET API UNAVAILABLE"})}
$("close").onclick=()=>$("viewer").classList.add("hidden");$("near").onclick=()=>loadPhotos(lat,lng);
$("satLayer").onchange=e=>{if(e.target.checked){if(!sat)sat=nasa("MODIS_Terra_CorrectedReflectance_TrueColor");sat.addTo(map);$("satStatus").textContent="ONLINE"}else if(sat){map.removeLayer(sat);$("satStatus").textContent="STANDBY"}};
$("cloudLayer").onchange=e=>{if(e.target.checked){if(!cloud)cloud=nasa("MODIS_Terra_Cloud_Optical_Thickness",true,.5);cloud.addTo(map)}else if(cloud)map.removeLayer(cloud)};
$("streetLayer").onchange=e=>{if(e.target.checked)loadPhotos(lat,lng)};
document.querySelectorAll(".modes button").forEach(b=>b.onclick=()=>{document.querySelectorAll(".modes button").forEach(x=>x.classList.remove("active"));b.classList.add("active");if(b.dataset.mode==="sat"){$("satLayer").checked=true;$("satLayer").dispatchEvent(new Event("change"))}if(b.dataset.mode==="street")loadPhotos(lat,lng)});
async function search(q){if(!q)return;$("searchResult").textContent="QUERYING…";const c=q.split(",").map(Number);if(c.length===2&&c.every(Number.isFinite)){map.setView(c,15);selectPoint(c[0],c[1],"COORDINATE TARGET");$("searchResult").textContent="COORDINATE TARGET FOUND";return}try{const r=await fetch(`https://nominatim.openstreetmap.org/search?format=jsonv2&limit=1&q=${encodeURIComponent(q)}`),d=await r.json();if(!d.length){$("searchResult").textContent="NO RESULT";return}const a=+d[0].lat,b=+d[0].lon;map.setView([a,b],15);selectPoint(a,b,d[0].display_name);$("searchResult").textContent="LOCATION FOUND"}catch(e){$("searchResult").textContent="SEARCH SERVICE UNAVAILABLE"}}
$("go").onclick=()=>search($("q").value.trim());$("q").onkeydown=e=>{if(e.key==="Enter")search(e.target.value.trim())};
$("locate").onclick=()=>{if(!navigator.geolocation)return;$("device").textContent="REQUESTING…";navigator.geolocation.getCurrentPosition(p=>{lat=p.coords.latitude;lng=p.coords.longitude;map.setView([lat,lng],17);if(deviceMarker)map.removeLayer(deviceMarker);deviceMarker=L.marker([lat,lng]).addTo(map).bindPopup("TIPIDON // THIS DEVICE").openPopup();$("device").textContent="ONLINE";selectPoint(lat,lng,"MY DEVICE");},()=>{$("device").textContent="DENIED"})};
function network(){const c=navigator.connection||navigator.mozConnection||navigator.webkitConnection;if($("quality").value!=="auto")return;if(!c)return;$("netText").textContent=(c.effectiveType||"AUTO").toUpperCase();if(c.saveData||["slow-2g","2g"].includes(c.effectiveType)){$("dataMode").textContent="LOW";$("netDot").style.color="#ffd166"}else if(c.effectiveType==="3g"){$("dataMode").textContent="NORMAL";$("netDot").style.color="#ffe066"}else{$("dataMode").textContent="HIGH";$("netDot").style.color="#00ff8c"}}$("quality").onchange=()=>{const v=$("quality").value;$("dataMode").textContent=v==="auto"?"SMART":v.toUpperCase()};network();setInterval(network,10000);setInterval(()=>$("clock").textContent=new Date().toLocaleTimeString(),1000);updateCoords();