const $=id=>document.getElementById(id);
let map,base,sat,roads,places,nasa,clouds,marker,gpsMarker,lat=6.5244,lng=3.3792;
const quality=()=>$("quality").value;
function esc(s){return String(s).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}
function init(){
 if(!window.L){$("ms").textContent="FAILED";return}
 base=L.tileLayer("https://tile.openstreetmap.org/{z}/{x}/{y}.png",{maxZoom:19,attribution:"© OpenStreetMap contributors"});
 sat=L.tileLayer("https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}",{maxZoom:19,attribution:"Sources: Esri, Maxar, Earthstar Geographics, and the GIS User Community"});
 roads=L.tileLayer("https://server.arcgisonline.com/ArcGIS/rest/services/Reference/World_Transportation/MapServer/tile/{z}/{y}/{x}",{maxZoom:19,attribution:"© Esri"});
 places=L.tileLayer("https://server.arcgisonline.com/ArcGIS/rest/services/Reference/World_Boundaries_and_Places/MapServer/tile/{z}/{y}/{x}",{maxZoom:19,attribution:"© Esri"});
 nasa=L.tileLayer.wms("https://gibs.earthdata.nasa.gov/wms/epsg3857/best/wms.cgi",{layers:"MODIS_Terra_CorrectedReflectance_TrueColor",format:"image/png",transparent:true,version:"1.1.1",attribution:"NASA GIBS"});
 cloud=L.tileLayer.wms("https://gibs.earthdata.nasa.gov/wms/epsg3857/nrt/wms.cgi",{layers:"MODIS_Terra_Cloud_Optical_Thickness",format:"image/png",transparent:true,version:"1.1.1",opacity:.45,attribution:"NASA GIBS"});
 map=L.map("map",{preferCanvas:true,minZoom:2,maxZoom:19}).setView([lat,lng],7);base.addTo(map);roads.addTo(map);places.addTo(map);$("ms").textContent="ONLINE";update();
 map.on("click",e=>select(e.latlng.lat,e.latlng.lng,"MAP TARGET"));map.on("moveend zoomend",update);
}
function update(){$("coord").textContent=`LAT ${lat.toFixed(5)} / LNG ${lng.toFixed(5)} / Z ${map.getZoom()}`}
function select(a,b,name){lat=a;lng=b;if(marker)map.removeLayer(marker);marker=L.marker([a,b]).addTo(map).bindPopup(`<b>${esc(name)}</b><br>${a.toFixed(6)}, ${b.toFixed(6)}`).openPopup();$("place").innerHTML=`<b>${esc(name)}</b><small>${a.toFixed(6)}, ${b.toFixed(6)}</small>`;update();if(quality()!=="low")street(a,b)}
function clearBase(){[base,sat,roads,places].forEach(x=>{if(map.hasLayer(x))map.removeLayer(x)})}
function view(v){clearBase();if(v==="map"){base.addTo(map);if($("roads").checked){roads.addTo(map);places.addTo(map)}}else if(v==="sat"){sat.addTo(map)}else if(v==="hybrid"){sat.addTo(map);if($("roads").checked){roads.addTo(map);places.addTo(map)}}else{base.addTo(map);if($("roads").checked){roads.addTo(map);places.addTo(map)}street(lat,lng)}}
document.querySelectorAll("[data-view]").forEach(b=>b.onclick=()=>{document.querySelectorAll("[data-view]").forEach(x=>x.classList.remove("active"));b.classList.add("active");view(b.dataset.view)});
$("roads").onchange=()=>{view(document.querySelector(".buttons .active").dataset.view)}
$("nasa").onchange=e=>e.target.checked?nasa.addTo(map):map.removeLayer(nasa);$("clouds").onchange=e=>e.target.checked?cloud.addTo(map):map.removeLayer(cloud);
async function search(q){$("result").textContent="SEARCHING…";try{let c=q.split(",").map(Number);if(c.length===2&&c.every(Number.isFinite)){map.setView(c,15);select(c[0],c[1],"COORDINATE TARGET");$("result").textContent="FOUND";return}let r=await fetch("https://nominatim.openstreetmap.org/search?format=jsonv2&limit=1&q="+encodeURIComponent(q),{headers:{Accept:"application/json"}}),d=await r.json();if(!d.length){$("result").textContent="NO RESULT";return}let a=+d[0].lat,b=+d[0].lon;map.setView([a,b],15);select(a,b,d[0].display_name);$("result").textContent="FOUND"}catch(e){$("result").textContent="SEARCH ERROR"}}
$("go").onclick=()=>search($("q").value.trim());$("q").onkeydown=e=>e.key==="Enter"&&search(e.target.value.trim());
$("locate").onclick=()=>{if(!navigator.geolocation)return;$("gps").textContent="WAIT";navigator.geolocation.getCurrentPosition(p=>{lat=p.coords.latitude;lng=p.coords.longitude;map.setView([lat,lng],17);if(gpsMarker)map.removeLayer(gpsMarker);gpsMarker=L.marker([lat,lng]).addTo(map).bindPopup("TIPIDON // THIS DEVICE").openPopup();$("gps").textContent="ONLINE";select(lat,lng,"MY DEVICE")},()=>$("gps").textContent="DENIED")};
async function street(a,b){$("status").textContent="SEARCHING PUBLIC STREET IMAGERY…";$("is").textContent="QUERY";$("photos").innerHTML="";try{let r=await fetch(`https://api.openstreetcam.org/2.0/photo/?lat=${a}&lng=${b}&radius=500`),j=await r.json(),list=Array.isArray(j.result?.data)?j.result.data:[];if(!list.length){$("status").textContent="NO PUBLIC STREET COVERAGE FOUND";$("is").textContent="NONE";return}$("status").textContent=`FOUND ${Math.min(8,list.length)} IMAGE(S)`;$("is").textContent="ONLINE";list.slice(0,8).forEach(p=>{let src=p.lth_name||p.name||p.image||p.url||p.photo_url||p.fileurl;if(!src)return;let d=document.createElement("div");d.className="photo";d.innerHTML=`<img loading="lazy" src="${src}"><span>PUBLIC STREET IMAGE</span>`;d.onclick=()=>{$("big").src=src;$("cap").textContent="KARTAVIEW / PUBLIC STREET IMAGERY";$("viewer").classList.remove("hidden")};$("photos").appendChild(d)})}catch(e){$("is").textContent="OFFLINE";$("status").textContent="STREET SERVICE UNAVAILABLE"}}
$("views").onclick=()=>street(lat,lng);$("x").onclick=()=>$("viewer").classList.add("hidden");
$("ipgo").onclick=async()=>{let ip=$("ip").value.trim();if(!ip){$("ipout").textContent="Enter an IP address.";return}$("ipout").textContent="LOOKING UP…";try{let r=await fetch("https://ipwho.is/"+encodeURIComponent(ip)),d=await r.json();if(!d.success)throw 0;$("ipout").innerHTML=`<b>${esc(d.ip)}</b><br>${esc(d.city||"")} ${esc(d.region||"")} ${esc(d.country||"")}<br>ISP: ${esc(d.connection?.isp||"Unknown")}<br>Approx: ${Number(d.latitude).toFixed(4)}, ${Number(d.longitude).toFixed(4)}`;if(d.latitude&&d.longitude){map.setView([d.latitude,d.longitude],10);select(d.latitude,d.longitude,"APPROXIMATE IP LOCATION")}}catch(e){$("ipout").textContent="Lookup unavailable. IP geolocation is approximate."}};
function net(){let c=navigator.connection||navigator.webkitConnection||navigator.mozConnection;if(!c){$("net").textContent="● ONLINE · AUTO DATA";return}let q=c.saveData||/2g/.test(c.effectiveType||"")?"LOW":c.effectiveType==="3g"?"NORMAL":"HIGH";if(quality()!=="auto")q=quality().toUpperCase();$("net").textContent=`● ONLINE · ${q} DATA`;if(q==="LOW")$("status").textContent="DATA SAVER ACTIVE — imagery loads on request"}
$("quality").onchange=net;net();setInterval(net,10000);setInterval(()=>$("clock").textContent=new Date().toLocaleTimeString(),1000);window.addEventListener("load",init);